ШРИ-2018-2 Домашняя работа Мультимедиа.
hydrognomik/hw1 pull request #2
Opened 2018-10-13 14:00 UTC by hydrognomik

2018-10-18 15:57 UTC, tavriaforever commented
@hydrognomik 
Снова не хватило описания как это запустить локально

2018-10-18 17:20 UTC, tavriaforever requested changes
В целом задание сделано, но мне не нравится как организован скрипт, внешние переменные, сложные названия, целые цепочки, никаких комментариев и jsdoc-а

В идеале я хочу или чисто функиональный подход с чистыми функциями или es6 classes, в идеале конечно попробовать `typescript` если не пробовал его раньше. 

Нужно стремиться к тому, чтобы структура скрипта читалась просто, да очевидно что есть сложные места, но в целом все должно быть понять быстрее чем это происходит сейчас. 

класс – что-то в конструкторе инитится и так далее, тогда можно и тесты сверху накрутить и сделать это модулем и далее можно до бесконечности развивать, можно превратить в свой модуль а в конце ты все равно напишешь свой реакт.

В общем давай попробуем привести код в порядок и накидать каких-то комментариев к местам которые их требуют на твое усмотрение

2018-10-18 17:20 UTC, tavriaforever commented on src/client/desktop.blocks/stream/stream.scss
> +    * {
старайся всегда уходить от таких селекторов

2018-10-18 17:20 UTC, tavriaforever commented on src/client/desktop.blocks/stream/stream.scss
> +#brightness-indicator {
старайся не использовать в верстке `id` – особенно когда вопрос касается видео которое может оказать внутри другого `iframe`, их может оказаться более одного на странице. `id` в верстке – плохой тон

2018-10-18 17:20 UTC, tavriaforever commented on src/client/index.html
>          <nav class="menu">
не тяжело писать html? Прикрутил бы себе что-то, можно что-то легкое, а можно и реакт, лишь бы тебе было удобнее работать с этим

2018-10-18 17:20 UTC, tavriaforever commented on src/client/observation.html
> +  <div class="page__wrapper-content">
зачем нужны эти обертки?

2018-10-18 17:20 UTC, tavriaforever commented on src/client/observation.html
> +      <div class="main__header">Видеонаблюдение</div>
старайся использовать семантическую разметку, для заголовком `h1, h2 ....`

2018-10-18 17:20 UTC, tavriaforever commented on src/client/observation.html
> +            <label for="brightness">
такого `id` нет зачем это?

2018-10-18 17:20 UTC, tavriaforever commented on src/client/observation.html
> +                id="stream__brightness"
в идеале если уж надо использовать `id` ну например для `<label for="` обычно id генерируется чтобы случайно не совпасть

2018-10-18 17:20 UTC, tavriaforever commented on src/client/desktop.blocks/stream/stream.js
> +    video.src = 'https://video-dev.github.io/streams/x36xhzz/x36xhzz.m3u8';
хм, а чего здесь ссылку оставил из ридми библиотеки?

2018-10-18 17:20 UTC, tavriaforever commented on src/client/desktop.blocks/stream/stream.js
> +initVideo(
лучше в итераторе запустить видео из пачки ссылок

2018-10-18 17:20 UTC, tavriaforever commented on src/client/desktop.blocks/stream/stream.js
> +  document.getElementById('stream-1'),
лучше инкапсулировать поиск видео элемента внутри фукнции document.getElementById, вообще наверное даже лучше было бы найти все видео на странице, положить ссылку в какой-нибудь атрибут и здесь оставить более универсальный код, добавишь 5 видео в html – здесь уже ничего трогать не надо будет

2018-10-18 17:20 UTC, tavriaforever commented on src/client/desktop.blocks/stream/stream.js
> +  curStream.style.filter = `contrast(${1 + e.target.value / 100})`;
👍

2018-10-18 17:20 UTC, tavriaforever commented on src/client/desktop.blocks/stream/stream.js
> +  curStream.style.filter = `brightness(${1 + e.target.value / 100})`;
👍

2018-10-18 17:20 UTC, tavriaforever commented on src/client/desktop.blocks/stream/stream.js
> +  stream.onclick = onStreamClickHandler;
почему не `addEventListener` ?

2018-10-18 17:20 UTC, tavriaforever commented on src/client/desktop.blocks/stream/stream.js
> +  if (curStream) {
почему бы не упрощать и не писать просто `stream` ?

2018-10-18 17:20 UTC, tavriaforever commented on src/client/desktop.blocks/stream/stream.js
> +  curSource = sources[curStream.id];
а почему это называется `sources`? это же только про аудио

2018-10-18 17:20 UTC, tavriaforever commented on src/client/desktop.blocks/stream/stream.js
> +    transform: ['scale(0.5)', 'scale(1)']
👍

2018-10-18 17:20 UTC, tavriaforever commented on src/client/desktop.blocks/stream/stream.js
> +  canvasCtx.fillRect(
хорошо что не использовал сторонние библиотеки

2018-10-20 07:46 UTC, hydrognomik commented on src/client/observation.html
> +  <div class="page__wrapper-content">
Внутренняя нужна для прижимания футера к низу страницы. А наружную удалю 😃 .

2018-10-20 08:07 UTC, hydrognomik commented on src/client/desktop.blocks/stream/stream.js
> +  curSource = sources[curStream.id];
Источники звука.

2018-10-23 14:29 UTC, merged